### ISSUE TITLE
Carga de Javascript de bootstrap falla por valores default del content security policy en servidor (helmet).

### ISSUE THREAD

**Issue by ja60c** [pedroagont/tinyclone#7]
La carga del bootstrap bundle js se ve afectada por las directivas del Content Security Policy definidas en el servidor a través del middleware helmet, el cual agrega por default la directiva "script-src 'self'", lo que significa que sólo permite la carga de archivos del mismo servidor, evitando la carga de scripts externos como lo es el de bootstrap.

Se anexa mensaje en consola que se muestra en todas las páginas que necesita cargar este script:

`Refused to load the script 'https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js' because it violates the following Content Security Policy directive: "script-src 'self'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.`

**Comment by pedroagont** [comment]
Muy bien Jacqueline gracias por identificar este error.

Estuve revisando y parece que si comentamos el uso del middleware helmet en la línea 17 del archivo `app.js`, se corrige el error, lo que obviamente no queremos hacer ya que vulnera las demás políticas de seguridad.

``` javascript
...
// app.use(helmet()); // <<<< USO DE HELMET COMENTADO
...
```

Por esta razón, revisando la documentación de helmet, encontré la forma de únicamente modificar la directiva del Content Security Policy mientras dejamos todas las demás políticas con sus valores por default.

``` javascript
...
app.use(helmet());
app.use(
  helmet.contentSecurityPolicy({
    useDefaults: true,
    directives: {
      'script-src': ["'self'", 'cdn.jsdelivr.net']
    }
  })
);
...
```

Liga de documentación de helmet: https://helmetjs.github.io/
